name: working_hours
description: "Calculate working hour."
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: '>=3.2.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.10
  dio: ^5.4.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  fonts:
  - family: Murecho
    fonts:
      - asset: assets/fonts/Murecho/static/Murecho-Thin.ttf
        weight: 100
      - asset: assets/fonts/Murecho/static/Murecho-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Murecho/static/Murecho-Light.ttf
        weight: 300
      - asset: assets/fonts/Murecho/static/Murecho-Regular.ttf
        weight: 400
      - asset: assets/fonts/Murecho/static/Murecho-Medium.ttf
        weight: 500
      - asset: assets/fonts/Murecho/static/Murecho-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Murecho/static/Murecho-Bold.ttf
        weight: 700
      - asset: assets/fonts/Murecho/static/Murecho-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Murecho/static/Murecho-Black.ttf
        weight: 900
